- name: Preflight
  tags: always
  ansible.builtin.include_tasks: 00-preflight.yml

- name: Install CCP
  ansible.builtin.include_tasks: 01-install.yml

- name: Uninstall CCP
  tags:
    - uninstall
  ansible.builtin.include_tasks: 02-uninstall.yml
