name: demo
services:
  # emulation of physical servers
  server-0:
    # debian bullseye with sshd
    # pretty close to ubuntu 22.04
    image: minimum2scp/baseimage-bullseye
    ports:
      - "2022:22"
      # nox ports
      - "7771:7771"
      - "9991:9991"
      - "18080:18080"

  server-1:
    image: minimum2scp/baseimage-bullseye
    ports:
      - "2023:22"
      # nox ports
      - "7772-7773:7772-7773"
      - "9992-9993:9992-9993"
      - "18081-18082:18081-18082"

  # services needed for nox to work
  chain:
    image: fluencelabs/chain-rpc:0.2.20
    ports:
      - 8545:8545
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
