name: demo

networks:
  demo:
    ipam:
      driver: default
      config:
        - subnet: "172.30.10.0/24"

services:
  server-0:
    image: ubuntu-systemd:jammy
    build:
      context: ./
    tty: true
    ports:
      - "2200:22"
      # nox ports
      - "7771:7771"
      - "9991:9991"
      - "18080:18080"
    networks:
      demo:
        ipv4_address: 172.30.10.10

  server-1:
    image: ubuntu-systemd:jammy
    build:
      context: ./
    tty: true
    ports:
      - "2201:22"
      # nox ports
      - "7772-7773:7772-7773"
      - "9992-9993:9992-9993"
      - "18081-18082:18081-18082"
    networks:
      demo:
        ipv4_address: 172.30.10.11

  # services required for Nox to work
  chain-rpc:
    image: fluencelabs/chain-rpc:0.8.0
    ports:
      - 8545:8545
    volumes:
      - chain-rpc:/data
    environment:
      LOCAL_CHAIN_BLOCK_MINING_INTERVAL: 1
    healthcheck:
      test: "curl -s -X POST 'http://localhost:8545' -H 'Content-Type:
        application/json' --data '{\"jsonrpc\":\"2.0\",
        \"method\":\"eth_chainId\", \"params\":[], \"id\":1}' | jq -e '.result
        != null'"
      interval: 8s
      timeout: 10s
      retries: 20
    networks:
      demo:
        ipv4_address: 172.30.10.85

  chain-deploy-script:
    image: fluencelabs/chain-deploy-script:0.8.0
    environment:
      CHAIN_RPC_URL: http://chain-rpc:8545
      MAX_FAILED_RATIO: "9999"
      IS_MOCKED_RANDOMX: "true"
      MIN_DURATION: 0
    depends_on:
      chain-rpc:
        condition: service_healthy
    networks:
      demo:

  ipfs:
    image: docker.io/ipfs/kubo:v0.26.0
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    networks:
      demo:
        ipv4_address: 172.30.10.95
