servers = 2

Vagrant.configure(2) do |config|
  (0...servers).each do |i|
    config.vm.define "server-#{i}" do |server|
      server.vm.box = "ubuntu/jammy64"

      server.vm.provider "virtualbox" do |vb|
        vb.name = "server-#{i}"
        vb.memory = "1024"
      end

      server.vm.network "private_network", ip: "192.168.56.#{10+i}"

      # SSH port
      server.vm.network "forwarded_port", guest: 22, host: 2200 + i

      # Nox ports
      server.vm.network "forwarded_port", guest: 7771, host: ("777#{i}".to_i)
      server.vm.network "forwarded_port", guest: 9991, host: ("999#{i}".to_i)
      server.vm.network "forwarded_port", guest: 18080, host: ("1808#{i}".to_i)
    end
  end

  config.vm.define "network" do |network|
    network.vm.box = "ubuntu/jammy64"
    network.vm.provider "virtualbox" do |vb|
      vb.name = "network"
      vb.memory = "1024"
    end

    network.vm.network "private_network", ip: "192.168.56.100"

    # SSH port
    network.vm.network "forwarded_port", guest: 22, host: 2299
    # IPFS and chain-rpc ports
    network.vm.network "forwarded_port", guest: 5001, host: 5001
    network.vm.network "forwarded_port", guest: 4001, host: 4001
    network.vm.network "forwarded_port", guest: 8545, host: 8545

    network.vm.provision "ansible" do |ansible|
      ansible.playbook = "vagrant/bootstrap.yml"
      ansible.galaxy_role_file = "vagrant/requirements.yml"
    end
  end
end
