ansible:
  # Settings for variable formatting rule (ANSIBLE0004)
  double-braces:
    max-spaces-inside: 1
    min-spaces-inside: 1

  # List of allowed literal bools (ANSIBLE0014)
  literal-bools:
    - "true"
    - "false"

# If you would like to force colored output (e.g. non-tty)
# set environment variable `PY_COLORS=1`
logging:
  level: "warning"

rules:
  version: "0.2"
  buildin: true
  exclude_files:
    - extentions/molecule/
    - **/files/**

  # Limit checks to given rule ID's
  # If empty all rules will be used.
  filter: []

  # Exclude given rule ID's from checks
  exclude_filter:
    # Do not force --- and ...
    - LINT0004
    - LINT0009

  # List of rule ID's that should be displayed as a warning instead of an error. By default,
  # only rules whose version is higher than the current default version are marked as warnings.
  # This list allows to degrade errors to warnings for each rule.
  warning_filter: []

  # All dotfiles (including hidden folders) are excluded by default.
  # You can disable this setting and handle dotfiles by yourself with `exclude_files`.
  ignore_dotfiles: true

  # List of directories to load standard rules from (defaults to build-in)
  standards: []

  # Standard version to use. Standard version set in a roles meta file
  # or playbook will takes precedence.
  version:

# Block to control included yamllint rules.
# See https://yamllint.readthedocs.io/en/stable/rules.html
yamllint:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments: enable
  comments-indentation: enable
  document-start: disable
  empty-lines:
    max: 3
    level: error
  hyphens:
    level: error
  indentation: enable
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  trailing-spaces: enable
  truthy: disable
