namespace: fluencelabs
name: provider
version: 0.2.0 # x-release-please-version
readme: README.md
authors:
  - Anatolios Laskaris <nahsi@nahsi.dev> (https://nahsi.dev)

description: Fluence provider toolkit used to setup and configure [Nox](https://github.com/fluencelabs/nox)
license_file: LICENSE

tags:
  - p2p
  - fluence
  - cloud
  - compute
  - web3

repository: https://github.com/fluencelabs/ansible/
documentation: https://github.com/fluencelabs/ansibe/tree/main/README.md
homepage: https://github.com/fluencelabs/ansible/
issues: https://github.com/fluencelabs/ansible/issues
