- name: Preflight
  tags: always
  include_tasks: 00-preflight.yml

- name: Install promtail
  include_tasks: 01-install.yml

- name: Uninstall promtail
  tags:
    - uninstall
  include_tasks: 02-uninstall.yml
