- name: stop nox
  tags:
    - never
    - uninstall
  ansible.builtin.systemd:
    name: nox
    state: stopped
    enabled: false

- name: delete nox directory
  tags:
    - never
    - uninstall
  ansible.builtin.file:
    path: "{{ nox_dir }}"
    state: absent

- name: cleanup VMs if any
  tags:
    - never
    - uninstall
  block:
    - name: List all VMs
      community.libvirt.virt:
        command: list_vms
      register: all_vms

    - name: "Destroy vm {{ item }}"
      community.libvirt.virt:
        name: "{{ item }}"
        command: destroy
      loop: "{{ all_vms.list_vms }}"

    - name: "Undefine vm {{ item }}"
      community.libvirt.virt:
        name: "{{ item }}"
        command: undefine
      loop: "{{ all_vms.list_vms }}"
