- name: Preflight
  tags: always
  ansible.builtin.include_tasks: 00-preflight.yml

- name: Install Nox
  ansible.builtin.include_tasks: 01-install.yml

- name: Uninstall Nox
  tags:
    - uninstall
  ansible.builtin.include_tasks: 02-uninstall.yml
