vm_remote_host: info-catcher.fluence.dev
vm_name: sandbox
vm_image_url: https://fluence-os-images.fra1.digitaloceanspaces.com/sandbox/latest/image.qcow2
vm_image_local_path: /var/lib/libvirt/qemu/images/{{ vm_name }}.qcow2
vm_libvirt_user: libvirt-qemu
vm_libvirt_group: kvm

vm_cpu_reserved: 1
vm_ram_reserved: 1024

vm_options:
  - cpu: "host"
  - vcpus: "{{ ansible_processor_vcpus - vm_cpu_reserved }}"
  - ram: "{{ ansible_memtotal_mb - vm_ram_reserved }}"
  - disk: "{{ vm_image_local_path }}"
  - network: "network=default"
  - os_variant: "ubuntu22.04"
  - graphics: "none"

vm_host_devices: []

vm_ip: 192.168.122.112

vm_iptables_map: |
      {
          "{{ vm_name }}": {
              "interface": "virbr0",
              "private_ip": "{{ vm_ip }}",
              "port_map": {
                  "tcp": [
                    80,
                    443
                  ],
                  "udp": [
                    80
                  ]
              },

              "port_range": [
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "tcp"
                  },
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "udp"
                  }
              ]
          }
      }
