vm_remote_host: info-catcher.fluence.dev
vm_name: sandbox
vm_image_url: https://fluence-os-images.fra1.digitaloceanspaces.com/sandbox/latest/image.qcow2
vm_image_local_path: /var/lib/libvirt/qemu/images/{{ vm_name }}.qcow2
vm_libvirt_user: libvirt-qemu
vm_libvirt_group: kvm

vm_iptables_map: |
      {
          "{{ vm_name }}": {
              "interface": "virbr0",
              "private_ip": "192.168.1.122",
              "port_map": {
                  "tcp": [
                    80,
                    443
                  ],
                  "udp": [
              80
                  ]
              },

              "port_range": [
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "tcp"
                  },
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "udp"
                  }
              ]
          }
      }
