vm_remote_host: info-catcher.fluence.dev
vm_name: sandbox
vm_image_url: https://fluence-os-images.fra1.digitaloceanspaces.com/sandbox/latest/image.qcow2

vm_cpu_reserved: 2
vm_ram_reserved: 4096

vm_options_default:
  - cpu: "host"
  - vcpus: "{{ ansible_processor_vcpus - vm_cpu_reserved }}"
  - ram: "{{ ansible_memtotal_mb - vm_ram_reserved }}"
  - virt_type: 'kvm'
  - network: "network=default"
  - os_variant: "ubuntu22.04"
  - graphics: "none"
  - disk: "vol='sandbox/{{ vm_name }}',device=disk,bus=virtio,serial='root'"

vm_options: []
_vm_options: "{{ vm_options_default + vm_options }}"

vm_ip: 192.168.122.112

vm_iptables_map: |
      {
          "{{ vm_name }}": {
              "interface": "virbr0",
              "private_ip": "{{ vm_ip }}",
              "port_map": {
                  "tcp": [
                    80,
                    443,
                    [2222, 22]
                  ],
                  "udp": [
                    80
                  ]
              },

              "port_range": [
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "tcp"
                  },
                  {
                      "init_port": 1000,
                      "ports_num": 64535,
                      "protocol": "udp"
                  }
              ]
          }
      }
