- name: install required packages and libraries
  apt:
    name: "{{ package }}"
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
    state: present
  loop:
    - libhwloc-dev
    - curl
    - qemu-kvm
    - libvirt-daemon-system
    - virt-manager
    - python-lxml

  loop_control:
    loop_var: package
    label: "{{ package }}"

- name: enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
    daemon_reload: true
    
- name: enable default network
  community.libvirt.virt_net:
    autostart: true
    state: active
    name: default
