galaxy_info:
  namespace: fluencelabs
  role_name: vmsandboxing
  license: Apache-2.0
  author: Roman Nozdrin
  description: Install and setup Fluence-specific VM sandboxing method
  issue_tracker_url: https://github.com/fluencelabs/ansible/issues
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - fluence
