driver:
  name: docker

platforms:
  - name: ubuntu-vm
    dockerfile: Dockerfile
    image: libvirt
    pre_build_image: false
    privileged: true
    command: ["/usr/bin/tini", "/usr/sbin/libvirtd"]
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml

verifier:
  name: testinfra
  directory: tests
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1
