- name: restart prometheus
  ansible.builtin.systemd:
    name: fluence-prometheus
    state: restarted
    daemon_reload: true

- name: reload prometheus
  ansible.builtin.systemd:
    name: fluence-prometheus
    state: reloaded
