- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libvirt-daemon-system
    - qemu-kvm
    - cloud-image-utils

- name: Satisfy software requirements
  import_role:
    name: jm1.libvirt.setup

- name: Create pool
  jm1.libvirt.pool:
    name: sandbox
    hardware:
     - type: dir
     - target: "/var/lib/libvirt/images/sandbox"
