- name: Copy iptables hook and schema to libvirt dir
  copy:
    src: "files/{{ item }}"
    dest: /etc/libvirt/hooks/
    mode: 0755
  loop:
    - iptables-hook
    - hooks.schema.json

- name: Create a symlink to trigger libvirt hook
  file:
    src: /etc/libvirt/hooks/iptables-hook
    dest: /etc/libvirt/hooks/qemu
    state: link

- name: Get IP address
  shell: virsh net-dhcp-leases default | grep ipv4 | awk '{ print $5} ' | cut -d'/' -f1
  register: vm_ip_raw

- name: Assign IP address to var
  set_fact:
    vm_ip: "{{ vm_ip_raw.stdout }}"

- debug:
    msg: "{{ vm_ip }}"

- name: Render hook template
  copy:
    content: "{{ vm_iptables_map }}"
    dest: /etc/libvirt/hooks/hooks.json

- name: Restart libvirtd
  service:
    name: libvirtd
    state: restarted