name: ansible

on:
  pull_request:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/ansible.yml"
      - "!**.md"

concurrency:
  group: "molecule-${{ github.ref }}"
  cancel-in-progress: true

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1
  FORCE_COLOR: 1

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Run ansible-later
  #       uses: patrickjahns/ansible-later-action@v1.3.0
  #       with:
  #         config: .later.yml

  #     - name: Run ansible-lint
  #       uses: reviewdog/action-ansiblelint@v1
  #       with:
  #         reporter: github-pr-check
  #         fail_on_error: true

  molecule:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ubuntu2204

    steps:
      - uses: actions/checkout@v4

      - name: Prepare for KVM usage
        run: |
          sudo apt-get install -y mkisofs qemu-system-x86 qemu-utils
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo usermod -a -G kvm $USER

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip

      - name: Install python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run ${{ matrix.scenario }} scenario
        run: molecule test --scenario-name "${{ matrix.scenario }}"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
